### ISSUE TITLE
Add feature for asking the bot questions, and having it give incorrect answers

### ISSUE THREAD

**Issue by Nyhilo** [Magimatt/BakaNinja-bot#5]
Similar to a talked about feature where the bot just attempts to give real answers to questions, this alternate command should give deliberately incorrect answers.

For example:
"Who was the king of Sumeria?"
"5 apples."

This should use the question text as a seed (optionally normalized, for capitalization, punctuation, etc.), so that it always returns the same incorrect answer for the same question.

**Comment by Magimatt** [comment]
No, this is a bad idea.
